//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不能找到名称为{0}的配置集合元素 的本地化字符串。
        /// </summary>
        internal static string CanNotFindNamedConfigElement {
            get {
                return ResourceManager.GetString("CanNotFindNamedConfigElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能在Xml节点{0}下找到{1} 的本地化字符串。
        /// </summary>
        internal static string CanNotFindXmlNode {
            get {
                return ResourceManager.GetString("CanNotFindXmlNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能在配置文件中找到配置节&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string CanNotFoundConfigSection {
            get {
                return ResourceManager.GetString("CanNotFoundConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能在配置文件中找到配置节&quot;{0}&quot;的详细定义部分 的本地化字符串。
        /// </summary>
        internal static string CanNotFoundConfigSectionElement {
            get {
                return ResourceManager.GetString("CanNotFoundConfigSectionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xml节点{0}转换到属性{1}出错，{2} 的本地化字符串。
        /// </summary>
        internal static string ConvertXmlNodeToPropertyError {
            get {
                return ResourceManager.GetString("ConvertXmlNodeToPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp: {timestamp}
        ///Title: {title}
        ///EventID: {eventid}
        ///Message: {message}
        ///Priority: {priority}
        ///EventType: {eventtype}
        ///StackTrace: {newline}{stacktrace}
        ///Machine: {machine}
        ///Extended Properties: {newline}{dictionary({key} - {value}{newline})} 的本地化字符串。
        /// </summary>
        internal static string DefaultTextFormat {
            get {
                return ResourceManager.GetString("DefaultTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache项{0}失效了，失效的依赖条件类型是{1} 的本地化字符串。
        /// </summary>
        internal static string DependencyChanged {
            get {
                return ResourceManager.GetString("DependencyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已添加了具有相同键的项: {0} 的本地化字符串。
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用&apos;{0}&apos; 定义了相互冲突的路径&apos;{1}&apos; 和  &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionConflictPathDefinition {
            get {
                return ResourceManager.GetString("ExceptionConflictPathDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be null or an empty string. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The formatter type &apos;{0}&apos; of &apos;{1}&apos;  is invalid. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSerializationFormatterType {
            get {
                return ResourceManager.GetString("ExceptionSerializationFormatterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件&quot;{0}&quot;不存在 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meta中配置的全局配置文件&quot;{0}&quot;不存在 的本地化字符串。
        /// </summary>
        internal static string GlobalFileNotFound {
            get {
                return ResourceManager.GetString("GlobalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化类属性失败。错误信息：{0} 的本地化字符串。
        /// </summary>
        internal static string InitialPropertyError {
            get {
                return ResourceManager.GetString("InitialPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员{0}，对象映射时不支持的成员类型{1} 的本地化字符串。
        /// </summary>
        internal static string InvalidMemberInfoType {
            get {
                return ResourceManager.GetString("InvalidMemberInfoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meta文件&quot;{0}&quot;不存在 的本地化字符串。
        /// </summary>
        internal static string MetaFileNotFound {
            get {
                return ResourceManager.GetString("MetaFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Error: property {0} not found&gt; 的本地化字符串。
        /// </summary>
        internal static string ReflectedPropertyTokenNotFound {
            get {
                return ResourceManager.GetString("ReflectedPropertyTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RuntimeCacheDefault 的本地化字符串。
        /// </summary>
        internal static string RuntimeCacheDefault {
            get {
                return ResourceManager.GetString("RuntimeCacheDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串参数{0}不能为Null或空串 的本地化字符串。
        /// </summary>
        internal static string StringParamCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringParamCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能加载类型{0} 的本地化字符串。
        /// </summary>
        internal static string TypeLoadException {
            get {
                return ResourceManager.GetString("TypeLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型{0}必须是枚举类型 的本地化字符串。
        /// </summary>
        internal static string TypeMustBeEnum {
            get {
                return ResourceManager.GetString("TypeMustBeEnum", resourceCulture);
            }
        }
    }
}
