//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib.Data.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}不允许为空（Null Or Empty）。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotNull {
            get {
                return ResourceManager.GetString("ArgumentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能找到数据库连接名称为{0}的配置信息，请检查connectionManager配置节 的本地化字符串。
        /// </summary>
        internal static string CanNotFindConnectionName {
            get {
                return ResourceManager.GetString("CanNotFindConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能找到数据库连接信息为&quot;{0}&quot;所对应的dataProvider:&quot;{1}&quot;，请检查connectionManager配置节的dataProviders配置项 的本地化字符串。
        /// </summary>
        internal static string CanNotFindProviderName {
            get {
                return ResourceManager.GetString("CanNotFindProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段{0}转换到属性{1}出错，{2} 的本地化字符串。
        /// </summary>
        internal static string ConvertDataFieldToPropertyError {
            get {
                return ResourceManager.GetString("ConvertDataFieldToPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 配置的事件参数类型有误 的本地化字符串。
        /// </summary>
        internal static string DbEventTypeIsNotValidException {
            get {
                return ResourceManager.GetString("DbEventTypeIsNotValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前记录更新时异常 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute Scalar() 方法不支持TableDirect模式 的本地化字符串。
        /// </summary>
        internal static string ExecuteScalarNotSupportTableDirectException {
            get {
                return ResourceManager.GetString("ExecuteScalarNotSupportTableDirectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员{0}，对象映射时不支持的成员类型{1} 的本地化字符串。
        /// </summary>
        internal static string InvalidMemberInfoType {
            get {
                return ResourceManager.GetString("InvalidMemberInfoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oracle DB 中SQL语句多Table输出性能表现较差，故不支持输出多个TableName方法,如果需要查询返回多个DataTable请将其写成存储过程 的本地化字符串。
        /// </summary>
        internal static string OracleMultiTablesError {
            get {
                return ResourceManager.GetString("OracleMultiTablesError", resourceCulture);
            }
        }
    }
}
